name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: "${{ secrets.AWS_REGION }}"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS \
              --password-stdin 262435403757.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t 262435403757.dkr.ecr.us-east-1.amazonaws.com/batch-classifier:${{ github.sha }} fastapi_lambda
          docker tag 262435403757.dkr.ecr.us-east-1.amazonaws.com/batch-classifier:${{ github.sha }} 262435403757.dkr.ecr.us-east-1.amazonaws.com/batch-classifier:latest
          docker push 262435403757.dkr.ecr.us-east-1.amazonaws.com/batch-classifier:${{ github.sha }}
          docker push 262435403757.dkr.ecr.us-east-1.amazonaws.com/batch-classifier:latest
