name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: "${{ secrets.AWS_REGION }}"

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets['AWS_ACCESS_KEY_ID'] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets['AWS_SECRET_ACCESS_KEY'] }}
          AWS_REGION: ${{ secrets['AWS_REGION'] }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets['AWS_ACCOUNT_ID'] }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets['AWS_ACCOUNT_ID'] }}
          AWS_REGION: ${{ secrets['AWS_REGION'] }}
          ECR_REPOSITORY: ${{ secrets['ECR_REPOSITORY'] }}
        run: |
          docker build -t $ECR_REPOSITORY:latest fastapi_lambda
          docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
